spring:
  application:
    name: Mano
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/start_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: db_user
    password: db_user_password
  jpa:
    show-sql: true
    database: mysql

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret:
    key: dahee-new-project-maumnote-jwt-secret-key-abcdefghijklmnopqrstuvwxyz
