spring:
  application:
    name: Mano
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mano?serverTimezone=UTC&characterEncoding=UTF-8
    username: new_user
    password: new_user_password
  jpa:
    show-sql: true
    database: mysql


logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret:
    key: dahee-new-project-maumnote-jwt-secret-key-abcdefghijklmnopqrstuvwxyz

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-login-endpoint: true  # login 엔드포인트 Swagger에 노출