services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: temppassword
      MYSQL_DATABASE: start_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cleanup.sh:/docker-entrypoint-initdb.d/cleanup.sh
    ports:
      - "3307:3307"
    user: "root"  # root로 실행
